### ISSUE TITLE
builtins.TypeError: pack_chunk() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by ghost** [LavaPower/PyMine#1]
Unhandled error in Deferred:

Traceback (most recent call last):
  File "C:\python38\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\python38\lib\site-packages\quarry\net\http.py", line 23, in _callback
    d0.callback(json.loads(data.decode('ascii')))
  File "C:\python38\lib\site-packages\twisted\internet\defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "C:\python38\lib\site-packages\twisted\internet\defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "C:\python38\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\python38\lib\site-packages\quarry\net\server.py", line 116, in auth_ok
    self.player_joined()
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Player.py", line 26, in player_joined
    self.world.player_joined()
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Plugins\World.py", line 11, in player_joined
    self.send_chunk(x, z)
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Plugins\World.py", line 58, in send_chunk
    cdpacket = ChunkDataPacket(self.protocol, "r.0.0.mca", 0, 0, x, z)
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Packets\Packets.py", line 159, in __init__
    super(ChunkDataPacket, self).__init__(protocol.buff_type, "chunk_data", (
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Packets\Packet.py", line 6, in __init__
    self.datas = self.get_datas(self.infos)
  File "C:\Users\Gosha\Desktop\PyMine-master\Core\Packets\Packet.py", line 28, in get_datas
    liste.append(self.buff.pack_chunk(i[1], i[2]))
builtins.TypeError: pack_chunk() takes 2 positional arguments but 3 were given

**Comment by AlexisHuvier** [comment]
Hello, you must have a different version of quarry. This program is not kept up to date and may not work with the latest versions of the libraries used.

**Comment by KweezyCode** [comment]
i've checked almost all versions of quarry and i think your code is broken

**Comment by AlexisHuvier** [comment]
Probably, but then again, the program is no longer being maintained... Maybe I'll pick it up again later, but I'll start from scratch.

**Comment by ghost** [comment]
okay then, thanks

**Comment by AlexisHuvier** [comment]
PyMine works again. But i didn't remake sending chunks for the moment.
